In [3]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/dirty_cafe_sales.csv")
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02


In [4]:
Quantity_array = df["Quantity"].to_numpy()

print(Quantity_array)

['2' '4' '4' ... '4' '3' '3']


  question no 1

In [8]:
import pandas as pd
import numpy as np

df["Quantity"] = pd.to_numeric(df["Quantity"], errors='coerce')
Quantity_array = df["Quantity"].to_numpy()

meanarr = np.mean(Quantity_array)
sumarr = np.sum(Quantity_array)
minarr = np.min(Quantity_array)
maxarr = np.max(Quantity_array)

print("Mean:", meanarr)
print("Sum:", sumarr)
print("Min:", minarr)
print("Max:", maxarr)

Mean: nan
Sum: nan
Min: nan
Max: nan


QUESTION NO 2

In [9]:
above_mean = Quantity_array[Quantity_array > meanarr]

print("Values above mean:", above_mean)

Values above mean: []


QUESTION NO 3

In [11]:
flat_array = np.arange(1, 13)

matrix = flat_array.reshape(3, 4)

print("3x4 Matrix   :", matrix)

3x4 Matrix   : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
a=np.array([1,2,3,4,])
b=np.array([5,6,7,8,])
verticallystack=np.vstack((a,b))
horizentallystack=np.hstack((a,b))
print("vertically stack   :",verticallystack)
print("horizentally stack   :",horizentallystack)

vertically stack   : [[1 2 3 4]
 [5 6 7 8]]
horizentally stack   : [1 2 3 4 5 6 7 8]


In [13]:
df.shape

(10000, 8)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Transaction ID    10000 non-null  object 
 1   Item              9667 non-null   object 
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9821 non-null   object 
 4   Total Spent       9827 non-null   object 
 5   Payment Method    7421 non-null   object 
 6   Location          6735 non-null   object 
 7   Transaction Date  9841 non-null   object 
dtypes: float64(1), object(7)
memory usage: 625.1+ KB


In [17]:
df.describe()

,Quantity
count,9521.000000
mean,3.028463
std,1.419007
min,1.000000
25%,2.000000
50%,3.000000
75%,4.000000
max,5.000000


In [18]:
df.isnull().sum()

,0
Transaction ID,0
Item,333
Quantity,479
Price Per Unit,179
Total Spent,173
Payment Method,2579
Location,3265
Transaction Date,159


SELECTING AND FILTERING

In [26]:
df["Price Per Unit"]=pd.to_numeric(df["Price Per Unit"],errors="coerce")
avg_amount=df["Price Per Unit"].mean()
result=df[df["Price Per Unit"]> avg_amount]
print(result)

     Transaction ID      Item  Quantity  Price Per Unit Total Spent  \
1       TXN_4977031      Cake       4.0             3.0        12.0   
3       TXN_7034554     Salad       2.0             5.0        10.0   
5       TXN_2602893  Smoothie       5.0             4.0        20.0   
6       TXN_4433211   UNKNOWN       3.0             3.0         9.0   
7       TXN_6699534  Sandwich       4.0             4.0        16.0   
...             ...       ...       ...             ...         ...   
9991    TXN_3897619  Sandwich       3.0             4.0        12.0   
9992    TXN_2739140  Smoothie       4.0             4.0        16.0   
9993    TXN_4766549  Smoothie       2.0             4.0         NaN   
9994    TXN_7851634   UNKNOWN       4.0             4.0        16.0   
9999    TXN_6170729  Sandwich       3.0             4.0        12.0   

     Payment Method  Location Transaction Date  
1              Cash  In-store       2023-05-16  
3           UNKNOWN   UNKNOWN       2023-04-27  


In [30]:
filtered_data=df[(df["Price Per Unit"]>3) & (df["Payment Method"] == "cash")]
print("filtered data   :",filtered_data)

filtered data   : Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date]
Index: []


In [31]:
value1 = df.loc[1, "Item"]
print(value1)


Cake


In [32]:
value2 = df.iloc[1, 1]
print(value2)


Cake


yes i get the same output

In [33]:
df["Item"].fillna(df["Item"].mode()[0], inplace=True)
df["Quantity"].fillna(df["Quantity"].mean, inplace=True)
df["Price Per Unit"].fillna(df["Price Per Unit"].mode()[0], inplace=True)
df["Total Spent"].fillna(df["Total Spent"].mode()[0], inplace=True)
df["Payment Method"].fillna(df["Payment Method"].mode()[0], inplace=True)
df["Location"].fillna(df["Location"].mode()[0], inplace=True)
df["Transaction Date"].fillna(df["Transaction Date"].mode()[0], inplace=True)


/tmp/ipykernel_2127/704111075.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Item"].fillna(df["Item"].mode()[0], inplace=True)
/tmp/ipykernel_2127/704111075.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '<bound method Series.mean of 0       2.0
1       4.0
2       4.0
3       2.0
4       2.0
       ... 
9995    2.0
9996    3.0
9997    4.0
9998    3.0
9999    3.0
Name: Quantity, Length: 10000, dtype: float64>' has dtype incompatible

In [34]:
df.isnull().sum()

,0
Transaction ID,0
Item,0
Quantity,0
Price Per Unit,0
Total Spent,0
Payment Method,0
Location,0
Transaction Date,0


I personally fill the object columns by taking mode and fill numeric columns by taking mean abd then check so now after filing there is no missing value in the dataset

MODIFIYING AND CLEANING

In [38]:
for col in df.select_dtypes(include="object"):
    df[col] = df[col].astype(str).str.lower().str.strip()


In [39]:
import numpy as np

df.replace(["N/A", "none", "-"], np.nan, inplace=True)


In [41]:
df["Total Spent"] = pd.to_numeric(df["Total Spent"], errors="coerce")
median_value = df["Total Spent"].median()
df["Transaction Level"] = df["Total Spent"].apply(lambda x: "High" if x > median_value else "Low")


In [42]:
df=df.drop_duplicates().reset_index(drop=True)

In [43]:
df["Total Spent"] = pd.to_numeric(df["Total Spent"], errors="coerce")

item_summary = df.groupby("Item").agg(
    total_sales=pd.NamedAgg(column="Total Spent", aggfunc="sum"),
    average_transaction=pd.NamedAgg(column="Total Spent", aggfunc="mean")
).reset_index()

print(item_summary)


       Item  total_sales  average_transaction
0      cake      10047.0             9.075881
1    coffee       6880.0             6.083112
2    cookie       3184.0             3.020873
3     error       2495.5             8.849291
4     juice      13009.0             8.953200
5     salad      16719.0            14.994619
6  sandwich      13112.0            12.018332
7  smoothie      12664.0            12.153551
8       tea       4885.5             4.583021
9   unknown       2805.5             8.501515


In [45]:
payment_counts=df["Payment Method"].value_counts()
print(payment_counts.head(1))

Payment Method
digital wallet    4870
Name: count, dtype: int64
